spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cmtm4w2q8rts.ap-northeast-2.rds.amazonaws.com/my_celebrity
    username: admin
    password: sj991209
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
cloud:
  aws:
    s3:
      bucket: s3-bucket-cbnu
    credentials:
      access-key: AKIAYCZOUQUQEQTJGTLI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
